### ISSUE TITLE
Pretrained weights available?

### ISSUE THREAD

**Issue by 10wei1000** [ChgygLin/TrackNetV2-pytorch#1]
Hi
Thank you for your great effort! Could you please provide a pretrained weights file? Also, I wonder whether this weights file can be directly used to detect a tennis ball?

**Comment by ChgygLin** [comment]
> Hi Thank you for your great effort! Could you please provide a pretrained weights file? Also, I wonder whether this weights file can be directly used to detect a tennis ball?

Hi,10wei1000
I have converted the original tensorflow weight to pytorch weight, and update the ReadMe.And you can try the weight^_^

**Comment by ChgygLin** [comment]
@10wei1000 
Hi, I've released a pretrained weights [v0.1](https://github.com/ChgygLin/TrackNetV2-pytorch/releases).
